#!/usr/bin/env python3
"""Regenerate the Herdr wire types from a published Herdr release tag.

Four stages, in the order SCOPE.md section 3.2 sets out:

1. **Fetch** Herdr's ``herdr-api.schema.json`` at the given tag.
2. **Extract** the five sub-schemas into one self-contained document.
3. **Lift** the request envelope's ``id`` out of the way of the discriminator.
4. **Generate** with ``cargo-typify``, and write the committed output.

Every intermediate lands in ``target/codegen/``, which is already ignored by
git, so a failed run leaves its evidence behind without leaving anything to
commit.

Two entry points run exactly this module, so the documented one and the tested
one cannot drift apart::

    just sync-api v0.9.0
    python3 codegen/sync_api.py v0.9.0

The second exists because ``just`` is not installed on every machine that has
to be able to regenerate these types.

The output is byte-identical across runs for a given tag and a given
``cargo-typify``. It is *not* identical across typify versions, which is why
the version used is recorded in the generated header: an upgrade shows up as a
line in the diff a human is already required to read (SCOPE.md section 12).

Python 3.9 is the floor. This machine has no other interpreter.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import List

from emit_sweep import collect_cases, render, write_rust
from extract import DriftError, extract
from lift_envelope import lift

REPO_ROOT = Path(__file__).resolve().parent.parent
WORK_DIR = REPO_ROOT / "target" / "codegen"
CRATE = REPO_ROOT / "crates" / "herdr-plugin-kit"
GENERATED_RS = CRATE / "src" / "api" / "generated.rs"
SWEEP_RS = CRATE / "tests" / "method_sweep.rs"

#: Where Herdr publishes the schema. The tag keeps its leading ``v``, because
#: that is what Herdr's own release tags carry.
SCHEMA_URL = "https://raw.githubusercontent.com/herdrdev/herdr/{tag}/docs/next/api/herdr-api.schema.json"

#: The cargo-typify this pipeline was measured against. A different version is
#: allowed and only warned about, because upgrading is legitimate and the diff
#: review is the real gate.
PINNED_TYPIFY = "0.8.0"


def fetch(tag: str, destination: Path) -> None:
    """Download the schema at *tag*, failing closed on anything but success."""
    url = SCHEMA_URL.format(tag=tag)
    # --fail turns a 404 into a non-zero exit instead of a saved error page,
    # and the protocol and TLS floors stop a redirect downgrading the transport.
    command = ["curl", "--proto", "=https", "--tlsv1.2", "--fail", "--silent",
               "--show-error", "--location", "--output", str(destination), url]
    result = subprocess.run(command)
    if result.returncode != 0:
        raise DriftError(
            f"could not fetch {url}\n"
            f"Check that the tag exists and keeps its leading 'v'. Herdr's own "
            f"release tags carry one."
        )
    print(f"fetch: {destination.stat().st_size} bytes from {url}")


def typify_version() -> str:
    """Report the installed cargo-typify version, failing closed if absent."""
    try:
        result = subprocess.run(
            ["cargo", "typify", "--version"], capture_output=True, text=True, check=True
        )
    except (OSError, subprocess.CalledProcessError) as error:
        raise DriftError(
            f"cargo-typify is not available ({error}).\n"
            f"Install it with `cargo install cargo-typify --version {PINNED_TYPIFY}`.\n"
            f"It is needed only to regenerate. The crate itself builds without it."
        )
    return result.stdout.strip().split()[-1]


def generate(lifted: Path, destination: Path) -> None:
    """Run cargo-typify over the lifted schema."""
    result = subprocess.run(
        ["cargo", "typify", "--output", str(destination), str(lifted)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise DriftError(f"cargo typify failed:\n{result.stdout}\n{result.stderr}")


def banner(script: str, tag: str, protocol: int, schema_version: int, typify: str) -> str:
    """The provenance header both generated files carry.

    It records no timestamp, on purpose. A timestamp would make every run a
    diff, which would bury the changes a human is supposed to be reading.
    """
    return "\n".join([
        f"// @generated by codegen/{script} — do not edit by hand.",
        "//",
        "// Any hand edit is destroyed by the next regeneration, without a warning",
        "// and without a conflict. Change the schema or the pipeline instead.",
        "//",
        f"//   source:         {SCHEMA_URL.format(tag=tag)}",
        f"//   herdr tag:      {tag}",
        f"//   protocol:       {protocol}",
        f"//   schema version: {schema_version}",
        f"//   cargo-typify:   {typify}",
        "//",
        f"// Regenerate with `just sync-api {tag}`, or with",
        f"// `python3 codegen/sync_api.py {tag}` where `just` is not installed.",
        "",
    ])


def constants(tag: str, protocol: int, schema_version: int) -> str:
    """The three provenance constants SCOPE.md section 4.1 specifies.

    They are appended rather than inserted, because typify's own inner
    attributes have to stay the first items in the file and an insertion point
    is one more thing that can silently move.
    """
    return "\n".join([
        "",
        "// ---------------------------------------------------------------------------",
        "// Provenance. Generated from the same fetch as the types above.",
        "// ---------------------------------------------------------------------------",
        "",
        "/// The Herdr release tag these types were generated from.",
        f'pub const GENERATED_FOR_HERDR_TAG: &str = "{tag}";',
        "",
        "/// The API protocol version Herdr declared at that tag.",
        "///",
        "/// Compare it against the `protocol` a live `ping` returns. A mismatch is a",
        "/// diagnosis, never a hard failure: a plugin that still works must keep working.",
        f"pub const GENERATED_PROTOCOL: u32 = {protocol};",
        "",
        "/// The schema version Herdr declared at that tag.",
        f"pub const GENERATED_SCHEMA_VERSION: u32 = {schema_version};",
        "",
    ])


def sync(tag: str) -> None:
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    envelope_path = WORK_DIR / "herdr-api.schema.json"
    merged_path = WORK_DIR / "merged.json"
    lifted_path = WORK_DIR / "lifted.json"
    raw_path = WORK_DIR / "generated.raw.rs"

    installed = typify_version()
    if installed != PINNED_TYPIFY:
        print(
            f"sync-api: WARNING cargo-typify is {installed}, and this pipeline was "
            f"measured against {PINNED_TYPIFY}. Read the generated diff with care.",
            file=sys.stderr,
        )

    fetch(tag, envelope_path)
    envelope = json.loads(envelope_path.read_text(encoding="utf-8"))
    protocol = envelope["protocol"]
    schema_version = envelope["schema_version"]

    merged, roots = extract(envelope)
    merged_path.write_text(json.dumps(merged, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"extract: {len(merged['$defs'])} types from {len(roots)} sub-schemas")

    lifted = lift(merged)
    lifted_path.write_text(json.dumps(lifted, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    generate(lifted_path, raw_path)

    write_rust(
        GENERATED_RS,
        banner("sync_api.py", tag, protocol, schema_version, installed)
        + raw_path.read_text(encoding="utf-8")
        + constants(tag, protocol, schema_version),
    )
    print(f"generate: {GENERATED_RS.relative_to(REPO_ROOT)}")

    cases = collect_cases(lifted)
    write_rust(
        SWEEP_RS,
        render(cases, banner("emit_sweep.py", tag, protocol, schema_version, installed)),
    )
    print(f"emit-sweep: {len(cases)} methods -> {SWEEP_RS.relative_to(REPO_ROOT)}")


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("tag", help="the Herdr release tag, leading 'v' included")
    args = parser.parse_args(argv)

    try:
        sync(args.tag)
    except DriftError as error:
        print(f"sync-api: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
