// @generated by codegen/emit_sweep.py — do not edit by hand.
//
// Any hand edit is destroyed by the next regeneration, without a warning
// and without a conflict. Change the schema or the pipeline instead.
//
//   source:         https://raw.githubusercontent.com/herdrdev/herdr/v0.9.0/docs/next/api/herdr-api.schema.json
//   herdr tag:      v0.9.0
//   protocol:       22
//   schema version: 1
//   cargo-typify:   0.8.0
//
// Regenerate with `just sync-api v0.9.0`, or with
// `python3 codegen/sync_api.py v0.9.0` where `just` is not installed.

//! Every method discriminator reaches its own named variant.
//!
//! This file is the acceptance test for the lift stage in `codegen/`. Read
//! `codegen/lift_envelope.py` before changing anything here.
//!
//! The rows and the match arms below were derived from Herdr's schema, not
//! from the generated Rust. That is what makes this a test rather than a
//! restatement: `cargo-typify` derives the same variant names from the same
//! schema by its own route, so the two only agree when both are right.
//!
//! Note what is deliberately *not* asserted: a JSON round-trip. The exact
//! defect this file exists to catch round-trips perfectly, because the method
//! name survives as an opaque string while every variant collapses into one.

use herdr_plugin_kit::api::generated::RequestMethod;
use herdr_plugin_kit::api::Request;

/// One row per method: the wire discriminator, the variant it must reach, and
/// the smallest params object the schema accepts for it.
///
/// Smallest is on purpose. A fixture carrying optional fields would still pass
/// if a required field had been generated as optional.
const CASES: &[(&str, &str, &str)] = &[
    ("ping", "Ping", r#"{}"#),
    ("server.stop", "ServerStop", r#"{}"#),
    ("server.live_handoff", "ServerLiveHandoff", r#"{}"#),
    ("server.reload_config", "ServerReloadConfig", r#"{}"#),
    ("server.agent_manifests", "ServerAgentManifests", r#"{}"#),
    (
        "server.reload_agent_manifests",
        "ServerReloadAgentManifests",
        r#"{}"#,
    ),
    ("notification.show", "NotificationShow", r#"{"title": ""}"#),
    (
        "product_announcement.dismiss",
        "ProductAnnouncementDismiss",
        r#"{"version": "", "id": ""}"#,
    ),
    (
        "release_notes.dismiss",
        "ReleaseNotesDismiss",
        r#"{"version": ""}"#,
    ),
    ("command.invoke", "CommandInvoke", r#"{"command_id": ""}"#),
    (
        "client.window_title.set",
        "ClientWindowTitleSet",
        r#"{"title": ""}"#,
    ),
    (
        "client.window_title.clear",
        "ClientWindowTitleClear",
        r#"{}"#,
    ),
    (
        "client_shell.surface.set",
        "ClientShellSurfaceSet",
        r#"{"active": false}"#,
    ),
    ("session.snapshot", "SessionSnapshot", r#"{}"#),
    ("workspace.create", "WorkspaceCreate", r#"{}"#),
    ("workspace.list", "WorkspaceList", r#"{}"#),
    ("workspace.get", "WorkspaceGet", r#"{"workspace_id": ""}"#),
    (
        "workspace.focus",
        "WorkspaceFocus",
        r#"{"workspace_id": ""}"#,
    ),
    (
        "workspace.rename",
        "WorkspaceRename",
        r#"{"workspace_id": "", "label": ""}"#,
    ),
    (
        "workspace.move",
        "WorkspaceMove",
        r#"{"workspace_id": "", "insert_index": 0}"#,
    ),
    (
        "workspace.move_block",
        "WorkspaceMoveBlock",
        r#"{"workspace_ids": []}"#,
    ),
    (
        "workspace.report_metadata",
        "WorkspaceReportMetadata",
        r#"{"workspace_id": "", "source": "", "tokens": {}}"#,
    ),
    (
        "workspace.close",
        "WorkspaceClose",
        r#"{"workspace_id": ""}"#,
    ),
    ("worktree.list", "WorktreeList", r#"{}"#),
    ("worktree.create", "WorktreeCreate", r#"{}"#),
    ("worktree.open", "WorktreeOpen", r#"{}"#),
    (
        "worktree.remove",
        "WorktreeRemove",
        r#"{"workspace_id": ""}"#,
    ),
    ("tab.create", "TabCreate", r#"{}"#),
    ("tab.list", "TabList", r#"{}"#),
    ("tab.get", "TabGet", r#"{"tab_id": ""}"#),
    ("tab.focus", "TabFocus", r#"{"tab_id": ""}"#),
    ("tab.rename", "TabRename", r#"{"tab_id": "", "label": ""}"#),
    (
        "tab.move",
        "TabMove",
        r#"{"tab_id": "", "insert_index": 0}"#,
    ),
    ("tab.close", "TabClose", r#"{"tab_id": ""}"#),
    ("agent.list", "AgentList", r#"{}"#),
    ("agent.get", "AgentGet", r#"{"target": ""}"#),
    (
        "agent.read",
        "AgentRead",
        r#"{"target": "", "source": "visible"}"#,
    ),
    ("agent.explain", "AgentExplain", r#"{"target": ""}"#),
    (
        "agent.send_keys",
        "AgentSendKeys",
        r#"{"target": "", "keys": []}"#,
    ),
    ("agent.rename", "AgentRename", r#"{"target": ""}"#),
    ("agent.view.set", "AgentViewSet", r#"{"source": ""}"#),
    ("agent.view.clear", "AgentViewClear", r#"{}"#),
    ("agent.focus", "AgentFocus", r#"{"target": ""}"#),
    (
        "agent.start",
        "AgentStart",
        r#"{"name": "", "kind": "", "pane_id": ""}"#,
    ),
    (
        "agent.prompt",
        "AgentPrompt",
        r#"{"target": "", "text": ""}"#,
    ),
    ("agent.wait", "AgentWait", r#"{"target": ""}"#),
    ("pane.split", "PaneSplit", r#"{"direction": "right"}"#),
    ("pane.swap", "PaneSwap", r#"{}"#),
    (
        "pane.move",
        "PaneMove",
        r#"{"pane_id": "", "destination": {"type": "tab", "tab_id": "", "split": "right"}}"#,
    ),
    ("pane.zoom", "PaneZoom", r#"{}"#),
    ("pane.layout", "PaneLayout", r#"{}"#),
    ("pane.process_info", "PaneProcessInfo", r#"{}"#),
    ("layout.export", "LayoutExport", r#"{}"#),
    (
        "layout.apply",
        "LayoutApply",
        r#"{"root": {"type": "pane"}}"#,
    ),
    (
        "layout.set_split_ratio",
        "LayoutSetSplitRatio",
        r#"{"path": [], "ratio": 0}"#,
    ),
    ("pane.neighbor", "PaneNeighbor", r#"{"direction": "left"}"#),
    ("pane.edges", "PaneEdges", r#"{}"#),
    (
        "pane.focus_direction",
        "PaneFocusDirection",
        r#"{"direction": "left"}"#,
    ),
    ("pane.resize", "PaneResize", r#"{"direction": "left"}"#),
    (
        "pane.scroll",
        "PaneScroll",
        r#"{"pane_id": "", "offset_from_bottom": 0}"#,
    ),
    (
        "pane.edit_scrollback",
        "PaneEditScrollback",
        r#"{"pane_id": ""}"#,
    ),
    (
        "pane.selection.read",
        "PaneSelectionRead",
        r#"{"pane_id": "", "anchor": {"row": 0, "col": 0}, "cursor": {"row": 0, "col": 0}}"#,
    ),
    (
        "pane.copy_motion",
        "PaneCopyMotion",
        r#"{"pane_id": "", "cursor": {"row": 0, "col": 0}, "motion": "line_end"}"#,
    ),
    (
        "pane.copy_search",
        "PaneCopySearch",
        r#"{"pane_id": "", "query": "", "direction": "forward", "cursor": {"row": 0, "col": 0}, "content_revision": 0}"#,
    ),
    ("pane.list", "PaneList", r#"{}"#),
    ("pane.current", "PaneCurrent", r#"{}"#),
    ("pane.get", "PaneGet", r#"{"pane_id": ""}"#),
    ("pane.focus", "PaneFocus", r#"{"pane_id": ""}"#),
    (
        "pane.input.set",
        "PaneInputSet",
        r#"{"pane_id": "", "right_click": "herdr"}"#,
    ),
    (
        "pane.link.activate",
        "PaneLinkActivate",
        r#"{"pane_id": "", "viewport_row": 0, "col": 0}"#,
    ),
    ("pane.rename", "PaneRename", r#"{"pane_id": ""}"#),
    (
        "pane.send_text",
        "PaneSendText",
        r#"{"pane_id": "", "text": ""}"#,
    ),
    (
        "pane.send_keys",
        "PaneSendKeys",
        r#"{"pane_id": "", "keys": []}"#,
    ),
    ("pane.send_input", "PaneSendInput", r#"{"pane_id": ""}"#),
    (
        "pane.read",
        "PaneRead",
        r#"{"pane_id": "", "source": "visible"}"#,
    ),
    (
        "pane.graphics.set",
        "PaneGraphicsSet",
        r#"{"pane_id": "", "format": "png", "image_width": 0, "image_height": 0}"#,
    ),
    (
        "pane.graphics.clear",
        "PaneGraphicsClear",
        r#"{"pane_id": ""}"#,
    ),
    (
        "pane.graphics.info",
        "PaneGraphicsInfo",
        r#"{"pane_id": ""}"#,
    ),
    (
        "pane.report_agent",
        "PaneReportAgent",
        r#"{"pane_id": "", "source": "", "agent": "", "state": "idle"}"#,
    ),
    (
        "pane.report_agent_session",
        "PaneReportAgentSession",
        r#"{"pane_id": "", "source": "", "agent": ""}"#,
    ),
    (
        "pane.report_metadata",
        "PaneReportMetadata",
        r#"{"pane_id": "", "source": ""}"#,
    ),
    (
        "pane.clear_agent_authority",
        "PaneClearAgentAuthority",
        r#"{"pane_id": ""}"#,
    ),
    (
        "pane.release_agent",
        "PaneReleaseAgent",
        r#"{"pane_id": "", "source": "", "agent": ""}"#,
    ),
    ("pane.close", "PaneClose", r#"{"pane_id": ""}"#),
    ("popup.close", "PopupClose", r#"{}"#),
    (
        "events.subscribe",
        "EventsSubscribe",
        r#"{"subscriptions": []}"#,
    ),
    (
        "events.wait",
        "EventsWait",
        r#"{"match_event": {"event": "workspace_created"}}"#,
    ),
    (
        "pane.wait_for_output",
        "PaneWaitForOutput",
        r#"{"pane_id": "", "source": "visible", "match": {"type": "substring", "value": ""}}"#,
    ),
    ("integration.list", "IntegrationList", r#"{}"#),
    (
        "integration.install",
        "IntegrationInstall",
        r#"{"target": "pi"}"#,
    ),
    (
        "integration.uninstall",
        "IntegrationUninstall",
        r#"{"target": "pi"}"#,
    ),
    ("plugin.link", "PluginLink", r#"{"path": ""}"#),
    ("plugin.list", "PluginList", r#"{}"#),
    ("plugin.unlink", "PluginUnlink", r#"{"plugin_id": ""}"#),
    ("plugin.enable", "PluginEnable", r#"{"plugin_id": ""}"#),
    ("plugin.disable", "PluginDisable", r#"{"plugin_id": ""}"#),
    ("plugin.action.list", "PluginActionList", r#"{}"#),
    (
        "plugin.action.invoke",
        "PluginActionInvoke",
        r#"{"action_id": ""}"#,
    ),
    ("plugin.log.list", "PluginLogList", r#"{}"#),
    (
        "plugin.pane.open",
        "PluginPaneOpen",
        r#"{"plugin_id": "", "entrypoint": ""}"#,
    ),
    ("plugin.pane.focus", "PluginPaneFocus", r#"{"pane_id": ""}"#),
    ("plugin.pane.close", "PluginPaneClose", r#"{"pane_id": ""}"#),
];

/// Names the variant a value actually holds.
///
/// The match is exhaustive, so a variant that Herdr adds, renames, or drops
/// stops this file compiling until the sweep is regenerated.
fn variant_name(method: &RequestMethod) -> &'static str {
    match method {
        RequestMethod::Ping(_) => "Ping",
        RequestMethod::ServerStop(_) => "ServerStop",
        RequestMethod::ServerLiveHandoff(_) => "ServerLiveHandoff",
        RequestMethod::ServerReloadConfig(_) => "ServerReloadConfig",
        RequestMethod::ServerAgentManifests(_) => "ServerAgentManifests",
        RequestMethod::ServerReloadAgentManifests(_) => "ServerReloadAgentManifests",
        RequestMethod::NotificationShow(_) => "NotificationShow",
        RequestMethod::ProductAnnouncementDismiss(_) => "ProductAnnouncementDismiss",
        RequestMethod::ReleaseNotesDismiss(_) => "ReleaseNotesDismiss",
        RequestMethod::CommandInvoke(_) => "CommandInvoke",
        RequestMethod::ClientWindowTitleSet(_) => "ClientWindowTitleSet",
        RequestMethod::ClientWindowTitleClear(_) => "ClientWindowTitleClear",
        RequestMethod::ClientShellSurfaceSet(_) => "ClientShellSurfaceSet",
        RequestMethod::SessionSnapshot(_) => "SessionSnapshot",
        RequestMethod::WorkspaceCreate(_) => "WorkspaceCreate",
        RequestMethod::WorkspaceList(_) => "WorkspaceList",
        RequestMethod::WorkspaceGet(_) => "WorkspaceGet",
        RequestMethod::WorkspaceFocus(_) => "WorkspaceFocus",
        RequestMethod::WorkspaceRename(_) => "WorkspaceRename",
        RequestMethod::WorkspaceMove(_) => "WorkspaceMove",
        RequestMethod::WorkspaceMoveBlock(_) => "WorkspaceMoveBlock",
        RequestMethod::WorkspaceReportMetadata(_) => "WorkspaceReportMetadata",
        RequestMethod::WorkspaceClose(_) => "WorkspaceClose",
        RequestMethod::WorktreeList(_) => "WorktreeList",
        RequestMethod::WorktreeCreate(_) => "WorktreeCreate",
        RequestMethod::WorktreeOpen(_) => "WorktreeOpen",
        RequestMethod::WorktreeRemove(_) => "WorktreeRemove",
        RequestMethod::TabCreate(_) => "TabCreate",
        RequestMethod::TabList(_) => "TabList",
        RequestMethod::TabGet(_) => "TabGet",
        RequestMethod::TabFocus(_) => "TabFocus",
        RequestMethod::TabRename(_) => "TabRename",
        RequestMethod::TabMove(_) => "TabMove",
        RequestMethod::TabClose(_) => "TabClose",
        RequestMethod::AgentList(_) => "AgentList",
        RequestMethod::AgentGet(_) => "AgentGet",
        RequestMethod::AgentRead(_) => "AgentRead",
        RequestMethod::AgentExplain(_) => "AgentExplain",
        RequestMethod::AgentSendKeys(_) => "AgentSendKeys",
        RequestMethod::AgentRename(_) => "AgentRename",
        RequestMethod::AgentViewSet(_) => "AgentViewSet",
        RequestMethod::AgentViewClear(_) => "AgentViewClear",
        RequestMethod::AgentFocus(_) => "AgentFocus",
        RequestMethod::AgentStart(_) => "AgentStart",
        RequestMethod::AgentPrompt(_) => "AgentPrompt",
        RequestMethod::AgentWait(_) => "AgentWait",
        RequestMethod::PaneSplit(_) => "PaneSplit",
        RequestMethod::PaneSwap(_) => "PaneSwap",
        RequestMethod::PaneMove(_) => "PaneMove",
        RequestMethod::PaneZoom(_) => "PaneZoom",
        RequestMethod::PaneLayout(_) => "PaneLayout",
        RequestMethod::PaneProcessInfo(_) => "PaneProcessInfo",
        RequestMethod::LayoutExport(_) => "LayoutExport",
        RequestMethod::LayoutApply(_) => "LayoutApply",
        RequestMethod::LayoutSetSplitRatio(_) => "LayoutSetSplitRatio",
        RequestMethod::PaneNeighbor(_) => "PaneNeighbor",
        RequestMethod::PaneEdges(_) => "PaneEdges",
        RequestMethod::PaneFocusDirection(_) => "PaneFocusDirection",
        RequestMethod::PaneResize(_) => "PaneResize",
        RequestMethod::PaneScroll(_) => "PaneScroll",
        RequestMethod::PaneEditScrollback(_) => "PaneEditScrollback",
        RequestMethod::PaneSelectionRead(_) => "PaneSelectionRead",
        RequestMethod::PaneCopyMotion(_) => "PaneCopyMotion",
        RequestMethod::PaneCopySearch(_) => "PaneCopySearch",
        RequestMethod::PaneList(_) => "PaneList",
        RequestMethod::PaneCurrent(_) => "PaneCurrent",
        RequestMethod::PaneGet(_) => "PaneGet",
        RequestMethod::PaneFocus(_) => "PaneFocus",
        RequestMethod::PaneInputSet(_) => "PaneInputSet",
        RequestMethod::PaneLinkActivate(_) => "PaneLinkActivate",
        RequestMethod::PaneRename(_) => "PaneRename",
        RequestMethod::PaneSendText(_) => "PaneSendText",
        RequestMethod::PaneSendKeys(_) => "PaneSendKeys",
        RequestMethod::PaneSendInput(_) => "PaneSendInput",
        RequestMethod::PaneRead(_) => "PaneRead",
        RequestMethod::PaneGraphicsSet(_) => "PaneGraphicsSet",
        RequestMethod::PaneGraphicsClear(_) => "PaneGraphicsClear",
        RequestMethod::PaneGraphicsInfo(_) => "PaneGraphicsInfo",
        RequestMethod::PaneReportAgent(_) => "PaneReportAgent",
        RequestMethod::PaneReportAgentSession(_) => "PaneReportAgentSession",
        RequestMethod::PaneReportMetadata(_) => "PaneReportMetadata",
        RequestMethod::PaneClearAgentAuthority(_) => "PaneClearAgentAuthority",
        RequestMethod::PaneReleaseAgent(_) => "PaneReleaseAgent",
        RequestMethod::PaneClose(_) => "PaneClose",
        RequestMethod::PopupClose(_) => "PopupClose",
        RequestMethod::EventsSubscribe(_) => "EventsSubscribe",
        RequestMethod::EventsWait(_) => "EventsWait",
        RequestMethod::PaneWaitForOutput(_) => "PaneWaitForOutput",
        RequestMethod::IntegrationList(_) => "IntegrationList",
        RequestMethod::IntegrationInstall(_) => "IntegrationInstall",
        RequestMethod::IntegrationUninstall(_) => "IntegrationUninstall",
        RequestMethod::PluginLink(_) => "PluginLink",
        RequestMethod::PluginList(_) => "PluginList",
        RequestMethod::PluginUnlink(_) => "PluginUnlink",
        RequestMethod::PluginEnable(_) => "PluginEnable",
        RequestMethod::PluginDisable(_) => "PluginDisable",
        RequestMethod::PluginActionList(_) => "PluginActionList",
        RequestMethod::PluginActionInvoke(_) => "PluginActionInvoke",
        RequestMethod::PluginLogList(_) => "PluginLogList",
        RequestMethod::PluginPaneOpen(_) => "PluginPaneOpen",
        RequestMethod::PluginPaneFocus(_) => "PluginPaneFocus",
        RequestMethod::PluginPaneClose(_) => "PluginPaneClose",
    }
}

fn envelope(method: &str, params: &str) -> String {
    format!(
        r#"{{"id":"req-1","method":{},"params":{}}}"#,
        serde_json::to_string(method).unwrap(),
        params
    )
}

#[test]
fn every_method_reaches_its_own_named_variant() {
    assert_eq!(
        CASES.len(),
        102,
        "the sweep must cover every method Herdr declares"
    );

    for (method, expected, params) in CASES {
        let json = envelope(method, params);
        let request: Request = serde_json::from_str(&json)
            .unwrap_or_else(|error| panic!("{method} did not deserialize: {error}\n{json}"));

        assert_eq!(
            variant_name(&request.method),
            *expected,
            "{method} reached the wrong variant",
        );
        assert_eq!(request.id, "req-1", "{method} lost the envelope id");
    }
}

#[test]
fn an_unknown_method_is_rejected() {
    let json = envelope("no.such.method", "{}");
    let result: Result<Request, _> = serde_json::from_str(&json);
    assert!(
        result.is_err(),
        "an invented method was accepted, so the enum is untagged: {result:?}",
    );
}

#[test]
fn a_method_with_no_params_is_rejected() {
    let (method, _, _) = CASES[0];
    let json = format!(r#"{{"id":"req-1","method":"{method}"}}"#);
    let result: Result<Request, _> = serde_json::from_str(&json);
    assert!(
        result.is_err(),
        "{method} was accepted with no params at all"
    );
}

#[test]
fn a_method_with_empty_params_is_rejected_when_it_requires_some() {
    let demanding: Vec<_> = CASES
        .iter()
        .filter(|(_, _, params)| *params != "{}")
        .collect();
    assert!(
        !demanding.is_empty(),
        "no method declares a required param, so this test cannot discriminate",
    );

    for (method, _, _) in demanding {
        let json = envelope(method, "{}");
        let result: Result<Request, _> = serde_json::from_str(&json);
        assert!(result.is_err(), "{method} was accepted with empty params");
    }
}
