// @generated by codegen/emit_sweep.py — do not edit by hand.
//
// Any hand edit is destroyed by the next regeneration, without a warning
// and without a conflict. Change the schema or the pipeline instead.
//
//   source:         https://raw.githubusercontent.com/herdrdev/herdr/v0.9.0/docs/next/api/herdr-api.schema.json
//   herdr tag:      v0.9.0
//   protocol:       22
//   schema version: 1
//   cargo-typify:   0.8.0
//
// Regenerate with `just sync-api v0.9.0`, or with
// `python3 codegen/sync_api.py v0.9.0` where `just` is not installed.

//! Every result discriminator reaches its own named variant, and its own type.
//!
//! This file is the acceptance test for `codegen/split_results.py`, and the
//! response side's answer to `tests/method_sweep.rs`. Read both before
//! changing anything here.
//!
//! The rows, the match arms, and the type names below were derived from
//! Herdr's schema, not from the generated Rust. `cargo-typify` derives the
//! same names from the same schema by its own route, so the two only agree
//! when both are right.
//!
//! Three things are held up, and the last two exist because one schema branch
//! is now rendered twice: once as a variant of the union, and once as a type a
//! caller can name on its own.
//!
//! 1. Each discriminator reaches its own union variant. The `match` is
//!    exhaustive, so a variant Herdr adds, renames, or drops stops this file
//!    compiling until the sweep is regenerated.
//! 2. The two renderings agree. The same fixture deserializes through both,
//!    and both serialize back to the same JSON.
//! 3. A type refuses an answer tagged for another variant. That refusal is
//!    what makes naming one type safe: `workspace.move` answers
//!    `workspace_list`, so a caller who guesses the tag from the method name
//!    has to be told, rather than handed a wrong parse.
//!
//! Note what is deliberately *not* asserted: a JSON round-trip on its own. An
//! untagged enum round-trips perfectly while dispatching on shape instead of
//! on the tag, which is the defect SCOPE.md section 3.3 records on the request
//! side and section 3.5 records for two more encodings tried here.

use herdr_plugin_kit::api::generated::{
    AgentExplainAnswer, AgentInfoAnswer, AgentListAnswer, AgentManifestReloadAnswer,
    AgentManifestStatusAnswer, AgentPromptedAnswer, AgentStartedAnswer, AgentViewAnswer,
    ClientShellSurfaceSetAnswer, ClientWindowTitleAnswer, ConfigReloadAnswer,
    IntegrationInstallAnswer, IntegrationListAnswer, IntegrationUninstallAnswer, LayoutApplyAnswer,
    LayoutExportAnswer, LayoutSplitRatioSetAnswer, NotificationShowAnswer, OkAnswer,
    OutputMatchedAnswer, PaneCopyMotionAnswer, PaneCopySearchAnswer, PaneCurrentAnswer,
    PaneEdgesAnswer, PaneFocusDirectionAnswer, PaneGraphicsFrameAckAnswer, PaneGraphicsInfoAnswer,
    PaneInfoAnswer, PaneLayoutAnswer, PaneLinkActivatedAnswer, PaneListAnswer, PaneMoveAnswer,
    PaneNeighborAnswer, PaneProcessInfoAnswer, PaneReadAnswer, PaneResizeAnswer,
    PaneSelectionAnswer, PaneSwapAnswer, PaneZoomAnswer, PluginActionInvokedAnswer,
    PluginActionListAnswer, PluginDisabledAnswer, PluginEnabledAnswer, PluginLinkedAnswer,
    PluginListAnswer, PluginLogListAnswer, PluginPaneClosedAnswer, PluginPaneFocusedAnswer,
    PluginPaneOpenedAnswer, PluginUnlinkedAnswer, PongAnswer, ResponseResult,
    SessionSnapshotAnswer, SubscriptionStartedAnswer, TabCreatedAnswer, TabInfoAnswer,
    TabListAnswer, WaitMatchedAnswer, WorkspaceCreatedAnswer, WorkspaceInfoAnswer,
    WorkspaceListAnswer, WorktreeCreatedAnswer, WorktreeListAnswer, WorktreeOpenedAnswer,
    WorktreeRemovedAnswer,
};

/// One row per result: the wire discriminator, the union variant it must
/// reach, and the smallest result object the schema accepts for it.
///
/// Smallest is on purpose. A fixture carrying optional fields would still pass
/// if a required field had been generated as optional.
const CASES: &[(&str, &str, &str)] = &[
    (
        "pong",
        "Pong",
        r#"{"type": "pong", "version": "", "protocol": 0}"#,
    ),
    (
        "session_snapshot",
        "SessionSnapshot",
        r#"{"type": "session_snapshot", "snapshot": {"version": "", "protocol": 0, "workspaces": [], "tabs": [], "panes": [], "layouts": [], "agents": []}}"#,
    ),
    (
        "workspace_info",
        "WorkspaceInfo",
        r#"{"type": "workspace_info", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}}"#,
    ),
    (
        "workspace_created",
        "WorkspaceCreated",
        r#"{"type": "workspace_created", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#,
    ),
    (
        "workspace_list",
        "WorkspaceList",
        r#"{"type": "workspace_list", "workspaces": []}"#,
    ),
    (
        "worktree_list",
        "WorktreeList",
        r#"{"type": "worktree_list", "source": {"repo_key": "", "repo_name": "", "repo_root": "", "source_checkout_path": ""}, "worktrees": []}"#,
    ),
    (
        "worktree_created",
        "WorktreeCreated",
        r#"{"type": "worktree_created", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "worktree": {"path": "", "is_bare": false, "is_detached": false, "is_prunable": false, "is_linked_worktree": false, "label": ""}}"#,
    ),
    (
        "worktree_opened",
        "WorktreeOpened",
        r#"{"type": "worktree_opened", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "worktree": {"path": "", "is_bare": false, "is_detached": false, "is_prunable": false, "is_linked_worktree": false, "label": ""}, "already_open": false}"#,
    ),
    (
        "worktree_removed",
        "WorktreeRemoved",
        r#"{"type": "worktree_removed", "workspace_id": "", "path": "", "forced": false}"#,
    ),
    (
        "tab_info",
        "TabInfo",
        r#"{"type": "tab_info", "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}}"#,
    ),
    (
        "tab_created",
        "TabCreated",
        r#"{"type": "tab_created", "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#,
    ),
    ("tab_list", "TabList", r#"{"type": "tab_list", "tabs": []}"#),
    (
        "agent_info",
        "AgentInfo",
        r#"{"type": "agent_info", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}}"#,
    ),
    (
        "agent_started",
        "AgentStarted",
        r#"{"type": "agent_started", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}, "argv": []}"#,
    ),
    (
        "agent_prompted",
        "AgentPrompted",
        r#"{"type": "agent_prompted", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}}"#,
    ),
    (
        "agent_list",
        "AgentList",
        r#"{"type": "agent_list", "agents": []}"#,
    ),
    (
        "agent_view",
        "AgentView",
        r#"{"type": "agent_view", "active": false}"#,
    ),
    (
        "pane_info",
        "PaneInfo",
        r#"{"type": "pane_info", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#,
    ),
    (
        "pane_list",
        "PaneList",
        r#"{"type": "pane_list", "panes": []}"#,
    ),
    (
        "pane_current",
        "PaneCurrent",
        r#"{"type": "pane_current", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#,
    ),
    (
        "pane_swap",
        "PaneSwap",
        r#"{"type": "pane_swap", "swap": {"changed": false, "source_pane_id": "", "focused_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
    ),
    (
        "pane_move",
        "PaneMove",
        r#"{"type": "pane_move", "move_result": {"changed": false, "previous_pane_id": "", "previous_workspace_id": "", "previous_tab_id": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "target_layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}, "focused_pane_id": ""}}"#,
    ),
    (
        "pane_zoom",
        "PaneZoom",
        r#"{"type": "pane_zoom", "zoom": {"changed": false, "zoom_changed": false, "focus_changed": false, "pane_id": "", "focused_pane_id": "", "zoomed": false, "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
    ),
    (
        "pane_layout",
        "PaneLayout",
        r#"{"type": "pane_layout", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}"#,
    ),
    (
        "pane_process_info",
        "PaneProcessInfo",
        r#"{"type": "pane_process_info", "process_info": {"pane_id": ""}}"#,
    ),
    (
        "layout_export",
        "LayoutExport",
        r#"{"type": "layout_export", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#,
    ),
    (
        "layout_apply",
        "LayoutApply",
        r#"{"type": "layout_apply", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#,
    ),
    (
        "layout_split_ratio_set",
        "LayoutSplitRatioSet",
        r#"{"type": "layout_split_ratio_set", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#,
    ),
    (
        "pane_neighbor",
        "PaneNeighbor",
        r#"{"type": "pane_neighbor", "neighbor": {"pane_id": "", "direction": "left", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
    ),
    (
        "pane_edges",
        "PaneEdges",
        r#"{"type": "pane_edges", "edges": {"pane_id": "", "left": false, "right": false, "up": false, "down": false, "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
    ),
    (
        "pane_focus_direction",
        "PaneFocusDirection",
        r#"{"type": "pane_focus_direction", "focus": {"changed": false, "source_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
    ),
    (
        "pane_resize",
        "PaneResize",
        r#"{"type": "pane_resize", "resize": {"changed": false, "pane_id": "", "focused_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
    ),
    (
        "pane_read",
        "PaneRead",
        r#"{"type": "pane_read", "read": {"pane_id": "", "workspace_id": "", "tab_id": "", "source": "visible", "format": "text", "text": "", "revision": 0, "truncated": false}}"#,
    ),
    (
        "pane_selection",
        "PaneSelection",
        r#"{"type": "pane_selection", "pane_id": "", "text": ""}"#,
    ),
    (
        "pane_copy_motion",
        "PaneCopyMotion",
        r#"{"type": "pane_copy_motion", "pane_id": "", "cursor": {"row": 0, "col": 0}, "content_revision": 0}"#,
    ),
    (
        "pane_copy_search",
        "PaneCopySearch",
        r#"{"type": "pane_copy_search", "pane_id": "", "content_revision": 0, "matches": [], "total": 0}"#,
    ),
    (
        "pane_graphics_frame_ack",
        "PaneGraphicsFrameAck",
        r#"{"type": "pane_graphics_frame_ack", "sequence": 0, "revision": 0}"#,
    ),
    (
        "pane_graphics_info",
        "PaneGraphicsInfo",
        r#"{"type": "pane_graphics_info", "cell_width_px": 0, "cell_height_px": 0, "pane_visible": false}"#,
    ),
    (
        "agent_explain",
        "AgentExplain",
        r#"{"type": "agent_explain", "explain": null}"#,
    ),
    (
        "subscription_started",
        "SubscriptionStarted",
        r#"{"type": "subscription_started"}"#,
    ),
    (
        "wait_matched",
        "WaitMatched",
        r#"{"type": "wait_matched", "event": {"event": "workspace_created", "data": {"type": "workspace_created", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}}}}"#,
    ),
    (
        "output_matched",
        "OutputMatched",
        r#"{"type": "output_matched", "pane_id": "", "revision": 0, "read": {"pane_id": "", "workspace_id": "", "tab_id": "", "source": "visible", "format": "text", "text": "", "revision": 0, "truncated": false}}"#,
    ),
    (
        "notification_show",
        "NotificationShow",
        r#"{"type": "notification_show", "shown": false, "reason": "shown"}"#,
    ),
    (
        "client_window_title",
        "ClientWindowTitle",
        r#"{"type": "client_window_title", "changed": false, "reason": "set"}"#,
    ),
    (
        "integration_list",
        "IntegrationList",
        r#"{"type": "integration_list", "integrations": []}"#,
    ),
    (
        "integration_install",
        "IntegrationInstall",
        r#"{"type": "integration_install", "target": "pi", "details": {"messages": []}}"#,
    ),
    (
        "integration_uninstall",
        "IntegrationUninstall",
        r#"{"type": "integration_uninstall", "target": "pi", "details": {"messages": []}}"#,
    ),
    (
        "agent_manifest_reload",
        "AgentManifestReload",
        r#"{"type": "agent_manifest_reload", "manifests": []}"#,
    ),
    (
        "agent_manifest_status",
        "AgentManifestStatus",
        r#"{"type": "agent_manifest_status", "manifests": []}"#,
    ),
    (
        "plugin_linked",
        "PluginLinked",
        r#"{"type": "plugin_linked", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#,
    ),
    (
        "plugin_list",
        "PluginList",
        r#"{"type": "plugin_list", "plugins": []}"#,
    ),
    (
        "plugin_unlinked",
        "PluginUnlinked",
        r#"{"type": "plugin_unlinked", "plugin_id": "", "removed": false}"#,
    ),
    (
        "plugin_enabled",
        "PluginEnabled",
        r#"{"type": "plugin_enabled", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#,
    ),
    (
        "plugin_disabled",
        "PluginDisabled",
        r#"{"type": "plugin_disabled", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#,
    ),
    (
        "plugin_action_list",
        "PluginActionList",
        r#"{"type": "plugin_action_list", "actions": []}"#,
    ),
    (
        "plugin_action_invoked",
        "PluginActionInvoked",
        r#"{"type": "plugin_action_invoked", "action": {"plugin_id": "", "action_id": "", "title": "", "command": []}, "context": {}, "log": {"log_id": "", "plugin_id": "", "command": [], "status": "running", "started_unix_ms": 0}}"#,
    ),
    (
        "pane_link_activated",
        "PaneLinkActivated",
        r#"{"type": "pane_link_activated", "handled": false}"#,
    ),
    (
        "plugin_log_list",
        "PluginLogList",
        r#"{"type": "plugin_log_list", "logs": []}"#,
    ),
    (
        "plugin_pane_opened",
        "PluginPaneOpened",
        r#"{"type": "plugin_pane_opened", "plugin_pane": {"plugin_id": "", "entrypoint": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}}"#,
    ),
    (
        "plugin_pane_focused",
        "PluginPaneFocused",
        r#"{"type": "plugin_pane_focused", "plugin_pane": {"plugin_id": "", "entrypoint": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}}"#,
    ),
    (
        "plugin_pane_closed",
        "PluginPaneClosed",
        r#"{"type": "plugin_pane_closed", "pane_id": ""}"#,
    ),
    (
        "config_reload",
        "ConfigReload",
        r#"{"type": "config_reload", "status": "applied", "diagnostics": []}"#,
    ),
    (
        "client_shell_surface_set",
        "ClientShellSurfaceSet",
        r#"{"type": "client_shell_surface_set", "active": false, "projection_revision": 0}"#,
    ),
    ("ok", "Ok", r#"{"type": "ok"}"#),
];

/// Names the union variant a value actually holds.
fn variant_name(result: &ResponseResult) -> &'static str {
    match result {
        ResponseResult::Pong { .. } => "Pong",
        ResponseResult::SessionSnapshot { .. } => "SessionSnapshot",
        ResponseResult::WorkspaceInfo { .. } => "WorkspaceInfo",
        ResponseResult::WorkspaceCreated { .. } => "WorkspaceCreated",
        ResponseResult::WorkspaceList { .. } => "WorkspaceList",
        ResponseResult::WorktreeList { .. } => "WorktreeList",
        ResponseResult::WorktreeCreated { .. } => "WorktreeCreated",
        ResponseResult::WorktreeOpened { .. } => "WorktreeOpened",
        ResponseResult::WorktreeRemoved { .. } => "WorktreeRemoved",
        ResponseResult::TabInfo { .. } => "TabInfo",
        ResponseResult::TabCreated { .. } => "TabCreated",
        ResponseResult::TabList { .. } => "TabList",
        ResponseResult::AgentInfo { .. } => "AgentInfo",
        ResponseResult::AgentStarted { .. } => "AgentStarted",
        ResponseResult::AgentPrompted { .. } => "AgentPrompted",
        ResponseResult::AgentList { .. } => "AgentList",
        ResponseResult::AgentView { .. } => "AgentView",
        ResponseResult::PaneInfo { .. } => "PaneInfo",
        ResponseResult::PaneList { .. } => "PaneList",
        ResponseResult::PaneCurrent { .. } => "PaneCurrent",
        ResponseResult::PaneSwap { .. } => "PaneSwap",
        ResponseResult::PaneMove { .. } => "PaneMove",
        ResponseResult::PaneZoom { .. } => "PaneZoom",
        ResponseResult::PaneLayout { .. } => "PaneLayout",
        ResponseResult::PaneProcessInfo { .. } => "PaneProcessInfo",
        ResponseResult::LayoutExport { .. } => "LayoutExport",
        ResponseResult::LayoutApply { .. } => "LayoutApply",
        ResponseResult::LayoutSplitRatioSet { .. } => "LayoutSplitRatioSet",
        ResponseResult::PaneNeighbor { .. } => "PaneNeighbor",
        ResponseResult::PaneEdges { .. } => "PaneEdges",
        ResponseResult::PaneFocusDirection { .. } => "PaneFocusDirection",
        ResponseResult::PaneResize { .. } => "PaneResize",
        ResponseResult::PaneRead { .. } => "PaneRead",
        ResponseResult::PaneSelection { .. } => "PaneSelection",
        ResponseResult::PaneCopyMotion { .. } => "PaneCopyMotion",
        ResponseResult::PaneCopySearch { .. } => "PaneCopySearch",
        ResponseResult::PaneGraphicsFrameAck { .. } => "PaneGraphicsFrameAck",
        ResponseResult::PaneGraphicsInfo { .. } => "PaneGraphicsInfo",
        ResponseResult::AgentExplain { .. } => "AgentExplain",
        ResponseResult::SubscriptionStarted => "SubscriptionStarted",
        ResponseResult::WaitMatched { .. } => "WaitMatched",
        ResponseResult::OutputMatched { .. } => "OutputMatched",
        ResponseResult::NotificationShow { .. } => "NotificationShow",
        ResponseResult::ClientWindowTitle { .. } => "ClientWindowTitle",
        ResponseResult::IntegrationList { .. } => "IntegrationList",
        ResponseResult::IntegrationInstall { .. } => "IntegrationInstall",
        ResponseResult::IntegrationUninstall { .. } => "IntegrationUninstall",
        ResponseResult::AgentManifestReload { .. } => "AgentManifestReload",
        ResponseResult::AgentManifestStatus { .. } => "AgentManifestStatus",
        ResponseResult::PluginLinked { .. } => "PluginLinked",
        ResponseResult::PluginList { .. } => "PluginList",
        ResponseResult::PluginUnlinked { .. } => "PluginUnlinked",
        ResponseResult::PluginEnabled { .. } => "PluginEnabled",
        ResponseResult::PluginDisabled { .. } => "PluginDisabled",
        ResponseResult::PluginActionList { .. } => "PluginActionList",
        ResponseResult::PluginActionInvoked { .. } => "PluginActionInvoked",
        ResponseResult::PaneLinkActivated { .. } => "PaneLinkActivated",
        ResponseResult::PluginLogList { .. } => "PluginLogList",
        ResponseResult::PluginPaneOpened { .. } => "PluginPaneOpened",
        ResponseResult::PluginPaneFocused { .. } => "PluginPaneFocused",
        ResponseResult::PluginPaneClosed { .. } => "PluginPaneClosed",
        ResponseResult::ConfigReload { .. } => "ConfigReload",
        ResponseResult::ClientShellSurfaceSet { .. } => "ClientShellSurfaceSet",
        ResponseResult::Ok => "Ok",
    }
}

#[test]
fn every_result_discriminator_reaches_its_own_named_variant() {
    assert_eq!(
        CASES.len(),
        64,
        "the sweep must cover every result Herdr declares"
    );

    for (tag, expected, fixture) in CASES {
        let result: ResponseResult = serde_json::from_str(fixture)
            .unwrap_or_else(|error| panic!("{tag} did not deserialize: {error}\n{fixture}"));

        assert_eq!(
            variant_name(&result),
            *expected,
            "{tag} reached the wrong variant"
        );
    }
}

#[test]
fn a_result_type_this_build_does_not_know_is_rejected() {
    let result: Result<ResponseResult, _> =
        serde_json::from_str(r#"{"type":"invented_by_a_later_herdr"}"#);

    assert!(
        result.is_err(),
        "an invented result type was accepted, so the enum is untagged: {result:?}",
    );
}

#[test]
fn a_result_carrying_no_type_at_all_is_rejected() {
    // An untagged enum accepts this by matching whichever variant needs
    // nothing. A tagged one has nothing to dispatch on and says so.
    let result: Result<ResponseResult, _> = serde_json::from_str("{}");

    assert!(
        result.is_err(),
        "an untagged object was accepted as a result: {result:?}",
    );
}

/// Holds one variant's own type against the union arm it was split from.
macro_rules! mirrors {
    ($checked:ident, $answer:ty, $tag:literal, $fixture:literal, $mistagged:literal) => {{
        let union: ResponseResult = serde_json::from_str($fixture)
            .unwrap_or_else(|error| panic!("{} is not a union value: {}", $tag, error));
        let narrow: $answer = serde_json::from_str($fixture)
            .unwrap_or_else(|error| panic!("{} is not a {}: {}", $tag, stringify!($answer), error));

        assert_eq!(
            serde_json::to_value(&union).unwrap(),
            serde_json::to_value(&narrow).unwrap(),
            "{} serialises differently through {} than through the union",
            $tag,
            stringify!($answer),
        );

        let refused: Result<$answer, _> = serde_json::from_str($mistagged);
        assert!(
            refused.is_err(),
            "{} accepted {}, which is tagged for another variant",
            stringify!($answer),
            $mistagged,
        );

        $checked += 1;
    }};
}

#[test]
fn every_result_type_mirrors_the_union_variant_it_was_split_from() {
    let mut checked = 0usize;

    mirrors!(
        checked,
        PongAnswer,
        "pong",
        r#"{"type": "pong", "version": "", "protocol": 0}"#,
        r#"{"type": "session_snapshot", "version": "", "protocol": 0}"#
    );
    mirrors!(
        checked,
        SessionSnapshotAnswer,
        "session_snapshot",
        r#"{"type": "session_snapshot", "snapshot": {"version": "", "protocol": 0, "workspaces": [], "tabs": [], "panes": [], "layouts": [], "agents": []}}"#,
        r#"{"type": "workspace_info", "snapshot": {"version": "", "protocol": 0, "workspaces": [], "tabs": [], "panes": [], "layouts": [], "agents": []}}"#
    );
    mirrors!(
        checked,
        WorkspaceInfoAnswer,
        "workspace_info",
        r#"{"type": "workspace_info", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}}"#,
        r#"{"type": "workspace_created", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}}"#
    );
    mirrors!(
        checked,
        WorkspaceCreatedAnswer,
        "workspace_created",
        r#"{"type": "workspace_created", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#,
        r#"{"type": "workspace_list", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#
    );
    mirrors!(
        checked,
        WorkspaceListAnswer,
        "workspace_list",
        r#"{"type": "workspace_list", "workspaces": []}"#,
        r#"{"type": "worktree_list", "workspaces": []}"#
    );
    mirrors!(
        checked,
        WorktreeListAnswer,
        "worktree_list",
        r#"{"type": "worktree_list", "source": {"repo_key": "", "repo_name": "", "repo_root": "", "source_checkout_path": ""}, "worktrees": []}"#,
        r#"{"type": "worktree_created", "source": {"repo_key": "", "repo_name": "", "repo_root": "", "source_checkout_path": ""}, "worktrees": []}"#
    );
    mirrors!(
        checked,
        WorktreeCreatedAnswer,
        "worktree_created",
        r#"{"type": "worktree_created", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "worktree": {"path": "", "is_bare": false, "is_detached": false, "is_prunable": false, "is_linked_worktree": false, "label": ""}}"#,
        r#"{"type": "worktree_opened", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "worktree": {"path": "", "is_bare": false, "is_detached": false, "is_prunable": false, "is_linked_worktree": false, "label": ""}}"#
    );
    mirrors!(
        checked,
        WorktreeOpenedAnswer,
        "worktree_opened",
        r#"{"type": "worktree_opened", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "worktree": {"path": "", "is_bare": false, "is_detached": false, "is_prunable": false, "is_linked_worktree": false, "label": ""}, "already_open": false}"#,
        r#"{"type": "worktree_removed", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}, "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "worktree": {"path": "", "is_bare": false, "is_detached": false, "is_prunable": false, "is_linked_worktree": false, "label": ""}, "already_open": false}"#
    );
    mirrors!(
        checked,
        WorktreeRemovedAnswer,
        "worktree_removed",
        r#"{"type": "worktree_removed", "workspace_id": "", "path": "", "forced": false}"#,
        r#"{"type": "tab_info", "workspace_id": "", "path": "", "forced": false}"#
    );
    mirrors!(
        checked,
        TabInfoAnswer,
        "tab_info",
        r#"{"type": "tab_info", "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}}"#,
        r#"{"type": "tab_created", "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}}"#
    );
    mirrors!(
        checked,
        TabCreatedAnswer,
        "tab_created",
        r#"{"type": "tab_created", "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#,
        r#"{"type": "tab_list", "tab": {"tab_id": "", "workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "agent_status": "idle"}, "root_pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#
    );
    mirrors!(
        checked,
        TabListAnswer,
        "tab_list",
        r#"{"type": "tab_list", "tabs": []}"#,
        r#"{"type": "agent_info", "tabs": []}"#
    );
    mirrors!(
        checked,
        AgentInfoAnswer,
        "agent_info",
        r#"{"type": "agent_info", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}}"#,
        r#"{"type": "agent_started", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}}"#
    );
    mirrors!(
        checked,
        AgentStartedAnswer,
        "agent_started",
        r#"{"type": "agent_started", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}, "argv": []}"#,
        r#"{"type": "agent_prompted", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}, "argv": []}"#
    );
    mirrors!(
        checked,
        AgentPromptedAnswer,
        "agent_prompted",
        r#"{"type": "agent_prompted", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}}"#,
        r#"{"type": "agent_list", "agent": {"terminal_id": "", "agent_status": "idle", "workspace_id": "", "tab_id": "", "pane_id": "", "focused": false, "revision": 0}}"#
    );
    mirrors!(
        checked,
        AgentListAnswer,
        "agent_list",
        r#"{"type": "agent_list", "agents": []}"#,
        r#"{"type": "agent_view", "agents": []}"#
    );
    mirrors!(
        checked,
        AgentViewAnswer,
        "agent_view",
        r#"{"type": "agent_view", "active": false}"#,
        r#"{"type": "pane_info", "active": false}"#
    );
    mirrors!(
        checked,
        PaneInfoAnswer,
        "pane_info",
        r#"{"type": "pane_info", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#,
        r#"{"type": "pane_list", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#
    );
    mirrors!(
        checked,
        PaneListAnswer,
        "pane_list",
        r#"{"type": "pane_list", "panes": []}"#,
        r#"{"type": "pane_current", "panes": []}"#
    );
    mirrors!(
        checked,
        PaneCurrentAnswer,
        "pane_current",
        r#"{"type": "pane_current", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#,
        r#"{"type": "pane_swap", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}"#
    );
    mirrors!(
        checked,
        PaneSwapAnswer,
        "pane_swap",
        r#"{"type": "pane_swap", "swap": {"changed": false, "source_pane_id": "", "focused_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
        r#"{"type": "pane_move", "swap": {"changed": false, "source_pane_id": "", "focused_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#
    );
    mirrors!(
        checked,
        PaneMoveAnswer,
        "pane_move",
        r#"{"type": "pane_move", "move_result": {"changed": false, "previous_pane_id": "", "previous_workspace_id": "", "previous_tab_id": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "target_layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}, "focused_pane_id": ""}}"#,
        r#"{"type": "pane_zoom", "move_result": {"changed": false, "previous_pane_id": "", "previous_workspace_id": "", "previous_tab_id": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}, "target_layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}, "focused_pane_id": ""}}"#
    );
    mirrors!(
        checked,
        PaneZoomAnswer,
        "pane_zoom",
        r#"{"type": "pane_zoom", "zoom": {"changed": false, "zoom_changed": false, "focus_changed": false, "pane_id": "", "focused_pane_id": "", "zoomed": false, "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
        r#"{"type": "pane_layout", "zoom": {"changed": false, "zoom_changed": false, "focus_changed": false, "pane_id": "", "focused_pane_id": "", "zoomed": false, "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#
    );
    mirrors!(
        checked,
        PaneLayoutAnswer,
        "pane_layout",
        r#"{"type": "pane_layout", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}"#,
        r#"{"type": "pane_process_info", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}"#
    );
    mirrors!(
        checked,
        PaneProcessInfoAnswer,
        "pane_process_info",
        r#"{"type": "pane_process_info", "process_info": {"pane_id": ""}}"#,
        r#"{"type": "layout_export", "process_info": {"pane_id": ""}}"#
    );
    mirrors!(
        checked,
        LayoutExportAnswer,
        "layout_export",
        r#"{"type": "layout_export", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#,
        r#"{"type": "layout_apply", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#
    );
    mirrors!(
        checked,
        LayoutApplyAnswer,
        "layout_apply",
        r#"{"type": "layout_apply", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#,
        r#"{"type": "layout_split_ratio_set", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#
    );
    mirrors!(
        checked,
        LayoutSplitRatioSetAnswer,
        "layout_split_ratio_set",
        r#"{"type": "layout_split_ratio_set", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#,
        r#"{"type": "pane_neighbor", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "focused_pane_id": "", "root": {"type": "pane"}}}"#
    );
    mirrors!(
        checked,
        PaneNeighborAnswer,
        "pane_neighbor",
        r#"{"type": "pane_neighbor", "neighbor": {"pane_id": "", "direction": "left", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
        r#"{"type": "pane_edges", "neighbor": {"pane_id": "", "direction": "left", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#
    );
    mirrors!(
        checked,
        PaneEdgesAnswer,
        "pane_edges",
        r#"{"type": "pane_edges", "edges": {"pane_id": "", "left": false, "right": false, "up": false, "down": false, "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
        r#"{"type": "pane_focus_direction", "edges": {"pane_id": "", "left": false, "right": false, "up": false, "down": false, "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#
    );
    mirrors!(
        checked,
        PaneFocusDirectionAnswer,
        "pane_focus_direction",
        r#"{"type": "pane_focus_direction", "focus": {"changed": false, "source_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
        r#"{"type": "pane_resize", "focus": {"changed": false, "source_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#
    );
    mirrors!(
        checked,
        PaneResizeAnswer,
        "pane_resize",
        r#"{"type": "pane_resize", "resize": {"changed": false, "pane_id": "", "focused_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#,
        r#"{"type": "pane_read", "resize": {"changed": false, "pane_id": "", "focused_pane_id": "", "layout": {"workspace_id": "", "tab_id": "", "zoomed": false, "area": {"x": 0, "y": 0, "width": 0, "height": 0}, "focused_pane_id": "", "panes": [], "splits": []}}}"#
    );
    mirrors!(
        checked,
        PaneReadAnswer,
        "pane_read",
        r#"{"type": "pane_read", "read": {"pane_id": "", "workspace_id": "", "tab_id": "", "source": "visible", "format": "text", "text": "", "revision": 0, "truncated": false}}"#,
        r#"{"type": "pane_selection", "read": {"pane_id": "", "workspace_id": "", "tab_id": "", "source": "visible", "format": "text", "text": "", "revision": 0, "truncated": false}}"#
    );
    mirrors!(
        checked,
        PaneSelectionAnswer,
        "pane_selection",
        r#"{"type": "pane_selection", "pane_id": "", "text": ""}"#,
        r#"{"type": "pane_copy_motion", "pane_id": "", "text": ""}"#
    );
    mirrors!(
        checked,
        PaneCopyMotionAnswer,
        "pane_copy_motion",
        r#"{"type": "pane_copy_motion", "pane_id": "", "cursor": {"row": 0, "col": 0}, "content_revision": 0}"#,
        r#"{"type": "pane_copy_search", "pane_id": "", "cursor": {"row": 0, "col": 0}, "content_revision": 0}"#
    );
    mirrors!(
        checked,
        PaneCopySearchAnswer,
        "pane_copy_search",
        r#"{"type": "pane_copy_search", "pane_id": "", "content_revision": 0, "matches": [], "total": 0}"#,
        r#"{"type": "pane_graphics_frame_ack", "pane_id": "", "content_revision": 0, "matches": [], "total": 0}"#
    );
    mirrors!(
        checked,
        PaneGraphicsFrameAckAnswer,
        "pane_graphics_frame_ack",
        r#"{"type": "pane_graphics_frame_ack", "sequence": 0, "revision": 0}"#,
        r#"{"type": "pane_graphics_info", "sequence": 0, "revision": 0}"#
    );
    mirrors!(
        checked,
        PaneGraphicsInfoAnswer,
        "pane_graphics_info",
        r#"{"type": "pane_graphics_info", "cell_width_px": 0, "cell_height_px": 0, "pane_visible": false}"#,
        r#"{"type": "agent_explain", "cell_width_px": 0, "cell_height_px": 0, "pane_visible": false}"#
    );
    mirrors!(
        checked,
        AgentExplainAnswer,
        "agent_explain",
        r#"{"type": "agent_explain", "explain": null}"#,
        r#"{"type": "subscription_started", "explain": null}"#
    );
    mirrors!(
        checked,
        SubscriptionStartedAnswer,
        "subscription_started",
        r#"{"type": "subscription_started"}"#,
        r#"{"type": "wait_matched"}"#
    );
    mirrors!(
        checked,
        WaitMatchedAnswer,
        "wait_matched",
        r#"{"type": "wait_matched", "event": {"event": "workspace_created", "data": {"type": "workspace_created", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}}}}"#,
        r#"{"type": "output_matched", "event": {"event": "workspace_created", "data": {"type": "workspace_created", "workspace": {"workspace_id": "", "number": 0, "label": "", "focused": false, "pane_count": 0, "tab_count": 0, "active_tab_id": "", "agent_status": "idle"}}}}"#
    );
    mirrors!(
        checked,
        OutputMatchedAnswer,
        "output_matched",
        r#"{"type": "output_matched", "pane_id": "", "revision": 0, "read": {"pane_id": "", "workspace_id": "", "tab_id": "", "source": "visible", "format": "text", "text": "", "revision": 0, "truncated": false}}"#,
        r#"{"type": "notification_show", "pane_id": "", "revision": 0, "read": {"pane_id": "", "workspace_id": "", "tab_id": "", "source": "visible", "format": "text", "text": "", "revision": 0, "truncated": false}}"#
    );
    mirrors!(
        checked,
        NotificationShowAnswer,
        "notification_show",
        r#"{"type": "notification_show", "shown": false, "reason": "shown"}"#,
        r#"{"type": "client_window_title", "shown": false, "reason": "shown"}"#
    );
    mirrors!(
        checked,
        ClientWindowTitleAnswer,
        "client_window_title",
        r#"{"type": "client_window_title", "changed": false, "reason": "set"}"#,
        r#"{"type": "integration_list", "changed": false, "reason": "set"}"#
    );
    mirrors!(
        checked,
        IntegrationListAnswer,
        "integration_list",
        r#"{"type": "integration_list", "integrations": []}"#,
        r#"{"type": "integration_install", "integrations": []}"#
    );
    mirrors!(
        checked,
        IntegrationInstallAnswer,
        "integration_install",
        r#"{"type": "integration_install", "target": "pi", "details": {"messages": []}}"#,
        r#"{"type": "integration_uninstall", "target": "pi", "details": {"messages": []}}"#
    );
    mirrors!(
        checked,
        IntegrationUninstallAnswer,
        "integration_uninstall",
        r#"{"type": "integration_uninstall", "target": "pi", "details": {"messages": []}}"#,
        r#"{"type": "agent_manifest_reload", "target": "pi", "details": {"messages": []}}"#
    );
    mirrors!(
        checked,
        AgentManifestReloadAnswer,
        "agent_manifest_reload",
        r#"{"type": "agent_manifest_reload", "manifests": []}"#,
        r#"{"type": "agent_manifest_status", "manifests": []}"#
    );
    mirrors!(
        checked,
        AgentManifestStatusAnswer,
        "agent_manifest_status",
        r#"{"type": "agent_manifest_status", "manifests": []}"#,
        r#"{"type": "plugin_linked", "manifests": []}"#
    );
    mirrors!(
        checked,
        PluginLinkedAnswer,
        "plugin_linked",
        r#"{"type": "plugin_linked", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#,
        r#"{"type": "plugin_list", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#
    );
    mirrors!(
        checked,
        PluginListAnswer,
        "plugin_list",
        r#"{"type": "plugin_list", "plugins": []}"#,
        r#"{"type": "plugin_unlinked", "plugins": []}"#
    );
    mirrors!(
        checked,
        PluginUnlinkedAnswer,
        "plugin_unlinked",
        r#"{"type": "plugin_unlinked", "plugin_id": "", "removed": false}"#,
        r#"{"type": "plugin_enabled", "plugin_id": "", "removed": false}"#
    );
    mirrors!(
        checked,
        PluginEnabledAnswer,
        "plugin_enabled",
        r#"{"type": "plugin_enabled", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#,
        r#"{"type": "plugin_disabled", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#
    );
    mirrors!(
        checked,
        PluginDisabledAnswer,
        "plugin_disabled",
        r#"{"type": "plugin_disabled", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#,
        r#"{"type": "plugin_action_list", "plugin": {"plugin_id": "", "name": "", "version": "", "manifest_path": "", "plugin_root": "", "enabled": false}}"#
    );
    mirrors!(
        checked,
        PluginActionListAnswer,
        "plugin_action_list",
        r#"{"type": "plugin_action_list", "actions": []}"#,
        r#"{"type": "plugin_action_invoked", "actions": []}"#
    );
    mirrors!(
        checked,
        PluginActionInvokedAnswer,
        "plugin_action_invoked",
        r#"{"type": "plugin_action_invoked", "action": {"plugin_id": "", "action_id": "", "title": "", "command": []}, "context": {}, "log": {"log_id": "", "plugin_id": "", "command": [], "status": "running", "started_unix_ms": 0}}"#,
        r#"{"type": "pane_link_activated", "action": {"plugin_id": "", "action_id": "", "title": "", "command": []}, "context": {}, "log": {"log_id": "", "plugin_id": "", "command": [], "status": "running", "started_unix_ms": 0}}"#
    );
    mirrors!(
        checked,
        PaneLinkActivatedAnswer,
        "pane_link_activated",
        r#"{"type": "pane_link_activated", "handled": false}"#,
        r#"{"type": "plugin_log_list", "handled": false}"#
    );
    mirrors!(
        checked,
        PluginLogListAnswer,
        "plugin_log_list",
        r#"{"type": "plugin_log_list", "logs": []}"#,
        r#"{"type": "plugin_pane_opened", "logs": []}"#
    );
    mirrors!(
        checked,
        PluginPaneOpenedAnswer,
        "plugin_pane_opened",
        r#"{"type": "plugin_pane_opened", "plugin_pane": {"plugin_id": "", "entrypoint": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}}"#,
        r#"{"type": "plugin_pane_focused", "plugin_pane": {"plugin_id": "", "entrypoint": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}}"#
    );
    mirrors!(
        checked,
        PluginPaneFocusedAnswer,
        "plugin_pane_focused",
        r#"{"type": "plugin_pane_focused", "plugin_pane": {"plugin_id": "", "entrypoint": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}}"#,
        r#"{"type": "plugin_pane_closed", "plugin_pane": {"plugin_id": "", "entrypoint": "", "pane": {"pane_id": "", "terminal_id": "", "workspace_id": "", "tab_id": "", "focused": false, "agent_status": "idle", "revision": 0}}}"#
    );
    mirrors!(
        checked,
        PluginPaneClosedAnswer,
        "plugin_pane_closed",
        r#"{"type": "plugin_pane_closed", "pane_id": ""}"#,
        r#"{"type": "config_reload", "pane_id": ""}"#
    );
    mirrors!(
        checked,
        ConfigReloadAnswer,
        "config_reload",
        r#"{"type": "config_reload", "status": "applied", "diagnostics": []}"#,
        r#"{"type": "client_shell_surface_set", "status": "applied", "diagnostics": []}"#
    );
    mirrors!(
        checked,
        ClientShellSurfaceSetAnswer,
        "client_shell_surface_set",
        r#"{"type": "client_shell_surface_set", "active": false, "projection_revision": 0}"#,
        r#"{"type": "ok", "active": false, "projection_revision": 0}"#
    );
    mirrors!(
        checked,
        OkAnswer,
        "ok",
        r#"{"type": "ok"}"#,
        r#"{"type": "pong"}"#
    );

    assert_eq!(
        checked,
        CASES.len(),
        "every result in the sweep must have a type of its own",
    );
}
